### ISSUE TITLE
Not recreating tasks, not finding existing tasks when trying to edit, unable to create new tasks

### ISSUE THREAD

**Issue by Liekinloimu** [Kirska/Habitica_ToDoOvers#17]
As the header says. 

When i try to edit task, i get:
"ValueError at /edit_task_action/1852/
The view to_do_overs.views.edit_task_action didn't return an HttpResponse object. It returned None instead."  

and Traceback for it gives:

> Environment:
> 
> 
> Request Method: POST
> Request URL: https://kirska.pythonanywhere.com/edit_task_action/1852/
> 
> Django Version: 1.11.29
> Python Version: 2.7.12
> Installed Applications:
> ['to_do_overs.apps.ToDoOversConfig',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles']
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> 
> 
> Traceback:
> 
> File "/home/Kirska/.virtualenvs/Habitica_ToDoOvers-virtualenv/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
>   41.             response = get_response(request)
> 
> File "/home/Kirska/.virtualenvs/Habitica_ToDoOvers-virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
>   198.                 "returned None instead." % (callback.__module__, view_name)
> 
> Exception Type: ValueError at /edit_task_action/1852/
> Exception Value: The view to_do_overs.views.edit_task_action didn't return an HttpResponse object. It returned None instead.

Trying to create a new task returns "Invalid form of data" as the image shows:

![image](https://user-images.githubusercontent.com/76769666/103338390-f582df80-4a86-11eb-9198-e12f01fb4411.png)

**Comment by Kirska** [comment]
I just cleared out the session data, try it again

**Comment by Liekinloimu** [comment]
Some of the tasks are being recreated, but not all. I'm also still unable to edit or create new tasks

**Comment by Kirska** [comment]
It appears the problem is one of your tags having a character that Django can't translate. Tags get reloaded from Habitica when you go to create a task. Hopefully this helps you workaround it.

`DjangoUnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128). You passed in <Tags: [Bad Unicode data]> (<class 'to_do_overs.models.Tags'>)`

**Comment by Liekinloimu** [comment]
Thank you! Now it's working. One of the challenges I had participated apparently had an emoji in their tag, and that's what caused the problem.
