### ISSUE TITLE
FileNotFoundError at /login_api_key/ when running locally

### ISSUE THREAD

**Issue by msnjuegos** [Kirska/Habitica_ToDoOvers#22]
Hello! First of all, thanks for this amazing extension, it is very useful. I have tried to run this application locally by downloading the repository, installing the `requiments.txt` and creating a DATABASE with mysql according to the /Habitica_ToDoOvers/settings.py file.
Then I run the program with `python manage.py runserver` and put my Habitica credentials but the page shows an error:

> FileNotFoundError at /login_api_key/
> [Errno 2] No such file or directory: 'Habitica_ToDoOvers/to_do_overs/app_functions/cipher.bin'
> Request Method: | POST
> Request url: http://127.0.0.1:8000/login_api_key/
> Django Version: 3.2
> Exception Location: /home/alan/opt/Habitica_ToDoOvers-master/to_do_overs/app_functions/cipher_functions.py, line 39, in encrypt_text
> Python Executable: /usr/bin/python
> Python version: 3.9.2

I am a noob with all these tools, so maybe I did made a mistake.
Any help will be very appreciated.

**Comment by Kirska** [comment]
Hi, you need to open up the cipher_functions.py file, uncomment out the code at the very bottom, and run it to generate a cipher file. This is unique to every setup and only needs to be done once.

**Comment by Kirska** [comment]
Also note you'll need to separately set up the scheduled_script.py file to be run daily automatically in order for everything to work properly.
