### ISSUE TITLE
The tool lacks all functionality

### ISSUE THREAD

**Issue by Stryder76** [Kirska/Habitica_ToDoOvers#31]
After I go to: https://kirska.pythonanywhere.com/

I got a something went wrong error.

I've tried clearing my cookies.

![Cap111111t1ure](https://user-images.githubusercontent.com/50467604/233811510-46d64afa-b209-4968-b0cd-9d3a757cbaa4.PNG)

**Comment by Kirska** [comment]
this was due to python anywhere forcing me to upgrade OS, should be fine now
